# Generated by Django 5.2 on 2025-04-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='book',
            new_name='books',
        ),
    ]
